---
- name: setting up the basis for the cluster
  hosts: all
  become: true
  tasks:
    - name: Include variables
      include_vars:
        file: "{{ playbook_dir }}/vars/{{ item }}"
      with_items:
        - "all.yaml"

    - name: Setting the basis on all nodes
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/Roles/Pre_Setup
        - $PWD/Roles/Install_Docker
        - $PWD/Roles/Fluentbit_Setup
      when: mode ==  'fluentbit'

